name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Printing folders
        run: ls
      - name: Install Dependencies
        run: npm ci
    # 0. Checkout the code of the repository
    # 1. Install deps
    # 2. Execute Automated tests
